In [65]:
import pandas as pd

In [66]:
books = pd.read_csv(r"collaborative_recommend\Books.csv")
ratings = pd.read_csv(r"collaborative_recommend\Ratings.csv")
users = pd.read_csv(r"collaborative_recommend\Users.csv")

C:\Users\VAISHNO KUMAR\AppData\Local\Temp\ipykernel_9864\4255685568.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(r"collaborative_recommend\Books.csv")

In [67]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [68]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [69]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [70]:
df = books.merge(ratings,on="ISBN")

In [71]:
df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2,0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400,0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,41385,0
...,...,...,...,...,...,...,...,...,...,...
1031131,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,276463,7
1031132,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,276579,4
1031133,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,276680,0
1031134,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,276680,0
1031135,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,276680,0

In [72]:
final_df = df.merge(users, on="User-ID")

In [73]:
final_df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating,Location,Age
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2,0,"stockton, california, usa",18.0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5,"timmins, ontario, canada",NaN
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,8,0,"timmins, ontario, canada",NaN
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,8,0,"timmins, ontario, canada",NaN
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,8,0,"timmins, ontario, canada",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1031131,087004124X,Anthem,Ayn Rand,1966,Caxton Press,http://images.amazon.com/images/P/087004124X.0...,http://images.amazon.com/images/P/087004124X.0...,http://images.amazon.com/images/P/087004124X.0...,259589,8,"venice, florida, usa",19.0
1031132,158243123X,A Student of Weather,Elizabeth Hay,2001,Counterpoint Press,http://images.amazon.com/images/P/158243123X.0...,http://images.amazon.com/images/P/158243123X.0...,http://images.amazon.com/images/P/158243123X.0...,259591,8,"tioga, pennsylvania, usa",39.0
1031133,8485900057,Rimas y leyendas (ClÃƒÂ¡sicos Fraile ; 3),Gustavo Adolfo BÃƒÂ©cquer,1981,Ediciones Fraile,http://images.amazon.com/images/P/8485900057.0...,http://images.amazon.com/images/P/8485900057.0...,http://images.amazon.com/images/P/8485900057.0...,259614,10,"madrid, madrid, spain",22.0
1031134,0838934854,Anglo-American Cataloguing Rules,Michael Gorman,1998,American Library Association,http://images.amazon.com/images/P/0838934854.0...,http://images.amazon.com/images/P/0838934854.0...,http://images.amazon.com/images/P/0838934854.0...,259679,6,"grand prairie, texas, usa",27.0
1031135,3423300965,Texte zur Ethik.,Dieter Birnbacher,2003,Dtv,http://images.amazon.com/images/P/3423300965.0...,http://images.amazon.com/images/P/3423300965.0...,http://images.amazon.com/images/P/3423300965.0...,259920,0,"bielefeld, nordrhein-westfalen, germany",NaN

In [74]:
final_df.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L', 'User-ID', 'Book-Rating',
       'Location', 'Age'],
      dtype='object')

In [75]:
stat = final_df.groupby("User-ID").count()['Book-Rating']

In [76]:
import numpy as np

In [77]:
stat

User-ID
2          1
8         17
9          3
10         1
12         1
          ..
278846     1
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 92106, dtype: int64

In [78]:
for i in range(0,100,10):
    print("{} percentile is ".format(i), np.percentile(stat, i))
print("{} percentile is ".format(100),np.percentile(stat, 100))

0 percentile is  1.0
10 percentile is  1.0
20 percentile is  1.0
30 percentile is  1.0
40 percentile is  1.0
50 percentile is  1.0
60 percentile is  2.0
70 percentile is  3.0
80 percentile is  5.0
90 percentile is  13.0
100 percentile is  11144.0

In [79]:
for i in range(90,100,1):
    print("{} percentile is ".format(i), np.percentile(stat, i))
print("{} percentile is ".format(100), np.percentile(stat, 100))

90 percentile is  13.0
91 percentile is  15.0
92 percentile is  17.0
93 percentile is  20.0
94 percentile is  25.0
95 percentile is  31.0
96 percentile is  40.0
97 percentile is  56.0
98 percentile is  89.0
99 percentile is  180.0
100 percentile is  11144.0

In [80]:
for i in np.arange(0.0,1.0,0.1):
    print("{} percentile is ".format(float(99+i)), np.percentile(stat, float(99+i)))
print("{} percentile is ".format(100), np.percentile(stat, 100))

99.0 percentile is  180.0
99.1 percentile is  197.0
99.2 percentile is  220.0
99.3 percentile is  240.0
99.4 percentile is  274.0
99.5 percentile is  321.4750000000058
99.6 percentile is  388.0
99.7 percentile is  473.6849999999977
99.8 percentile is  667.3699999999808
99.9 percentile is  1093.0
100 percentile is  11144.0

In [81]:
x = stat[stat>100]

In [82]:
niche_users  = x.index

In [83]:
fitered = final_df[final_df["User-ID"].isin(niche_users)]

In [84]:
fitered

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating,Location,Age
80,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8,"n/a, n/a, n/a",NaN
81,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,11676,9,"n/a, n/a, n/a",NaN
82,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...,11676,8,"n/a, n/a, n/a",NaN
83,0771074670,Nights Below Station Street,David Adams Richards,1988,Emblem Editions,http://images.amazon.com/images/P/0771074670.0...,http://images.amazon.com/images/P/0771074670.0...,http://images.amazon.com/images/P/0771074670.0...,11676,0,"n/a, n/a, n/a",NaN
84,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,11676,9,"n/a, n/a, n/a",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
954156,0263827461,A Poor Relation (Historical Romance: Regency),Joanna Maitland,2001,Harlequin Mills &amp; Boon Ltd,http://images.amazon.com/images/P/0263827461.0...,http://images.amazon.com/images/P/0263827461.0...,http://images.amazon.com/images/P/0263827461.0...,163759,5,"abertillery, wales, united kingdom",37.0
954157,0263816575,Mistress of Madderlea (Historical Romance: Reg...,Mary Nichols,1999,Harlequin Mills &amp; Boon Ltd,http://images.amazon.com/images/P/0263816575.0...,http://images.amazon.com/images/P/0263816575.0...,http://images.amazon.com/images/P/0263816575.0...,163759,5,"abertillery, wales, united kingdom",37.0
954158,0440222974,A Fire in Heaven,Annee Carter,1998,Dell Publishing Company,http://images.amazon.com/images/P/0440222974.0...,http://images.amazon.com/images/P/0440222974.0...,http://images.amazon.com/images/P/0440222974.0...,163759,5,"abertillery, wales, united kingdom",37.0
954159,0373059191,Mr. Easy (Man Of The Month) (Silhouette Desir...,Cait London,1995,Silhouette,http://images.amazon.com/images/P/0373059191.0...,http://images.amazon.com/images/P/0373059191.0...,http://images.amazon.com/images/P/0373059191.0...,163759,4,"abertillery, wales, united kingdom",37.0
954160,0373760930,Groom Candidate (Man Of The Month/The Tallchi...,Cait London,1997,Silhouette,http://images.amazon.com/images/P/0373760930.0...,http://images.amazon.com/images/P/0373760930.0...,http://images.amazon.com/images/P/0373760930.0...,163759,4,"abertillery, wales, united kingdom",37.0

In [85]:
stat_book = fitered.groupby("Book-Title").count()['Book-Rating']

In [86]:
for i in range(0,100,10):
    print("{} percentile is ".format(i), np.percentile(stat_book, i))
print("{} percentile is ".format(100),np.percentile(stat_book, 100))

0 percentile is  1.0
10 percentile is  1.0
20 percentile is  1.0
30 percentile is  1.0
40 percentile is  1.0
50 percentile is  1.0
60 percentile is  2.0
70 percentile is  2.0
80 percentile is  3.0
90 percentile is  6.0
100 percentile is  556.0

In [87]:
for i in range(90,100,1):
    print("{} percentile is ".format(i), np.percentile(stat_book, i))
print("{} percentile is ".format(100), np.percentile(stat_book, 100))

90 percentile is  6.0
91 percentile is  6.0
92 percentile is  7.0
93 percentile is  8.0
94 percentile is  9.0
95 percentile is  10.0
96 percentile is  12.0
97 percentile is  16.0
98 percentile is  22.0
99 percentile is  35.0
100 percentile is  556.0

In [88]:
for i in np.arange(0.0,1.0,0.1):
    print("{} percentile is ".format(float(99+i)), np.percentile(stat_book, float(99+i)))
print("{} percentile is ".format(100), np.percentile(stat_book, 100))

99.0 percentile is  35.0
99.1 percentile is  38.0
99.2 percentile is  41.0
99.3 percentile is  45.0
99.4 percentile is  49.0
99.5 percentile is  55.0
99.6 percentile is  63.0
99.7 percentile is  74.0
99.8 percentile is  92.0
99.9 percentile is  122.0
100 percentile is  556.0

In [89]:
stat_book.describe()

count    178335.000000
mean          3.319012
std           9.040947
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max         556.000000
Name: Book-Rating, dtype: float64

In [90]:
y = stat_book[stat_book>35]
limelight_books = y.index

In [91]:
final = fitered[fitered["Book-Title"].isin(limelight_books)]

In [92]:
pivot_final = final.pivot_table(index='Book-Title', columns='User-ID',values='Book-Rating')

In [93]:
pivot_final.fillna(0, inplace=True)

In [94]:
pivot_final

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,275020,275970,276463,276680,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
from sklearn.metrics.pairwise import cosine_similarity

In [96]:
similarity_scores = cosine_similarity(pivot_final)

In [97]:
similarity_scores.shape

(1781, 1781)

### function

In [98]:
def recommend(book_name):
    index = np.where(pivot_final.index == book_name)[0][0]
    similar_item = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]
    data = []
    for i in similar_item:
        temp_df =  books[books['Book-Title'] == pivot_final.index[i[0]]]
        item = []
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        data.append(item)
    return data

In [99]:
recommend("The Handmaid's Tale")

[['AGE OF INNOCENCE (MOVIE TIE-IN)',
  'Edith Wharton',
  'http://images.amazon.com/images/P/002026478X.01.MZZZZZZZ.jpg'],
 ['The Bone Collector (Lincoln Rhyme Novels (Paperback))',
  'Jeff Deaver',
  'http://images.amazon.com/images/P/0451188454.01.MZZZZZZZ.jpg'],
 ['Bastard Out of Carolina',
  'Dorothy Allison',
  'http://images.amazon.com/images/P/0452269571.01.MZZZZZZZ.jpg'],
 ['The Awakening',
  'Kate Chopin',
  'http://images.amazon.com/images/P/055321330X.01.MZZZZZZZ.jpg'],
 ["The Kitchen God's Wife",
  'Amy Tan',
  'http://images.amazon.com/images/P/0399135782.01.MZZZZZZZ.jpg']]

In [100]:
final_df.drop_duplicates('Book-Title')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating,Location,Age
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2,0,"stockton, california, usa",18.0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5,"timmins, ontario, canada",NaN
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,8,0,"timmins, ontario, canada",NaN
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,8,0,"timmins, ontario, canada",NaN
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,8,0,"timmins, ontario, canada",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1031129,8441407487,Sobre La Utilidad y Los Perjuicios de La Historia,Friedrich Wilhelm Nietzsche,2000,Edaf,http://images.amazon.com/images/P/8441407487.0...,http://images.amazon.com/images/P/8441407487.0...,http://images.amazon.com/images/P/8441407487.0...,246590,6,"madrid, madrid, spain",20.0
1031130,0817310916,One Day in the Life of a Born Again Loser: And...,Helen Norris,2000,University of Alabama Press,http://images.amazon.com/images/P/0817310916.0...,http://images.amazon.com/images/P/0817310916.0...,http://images.amazon.com/images/P/0817310916.0...,259416,0,"parkton, maryland, usa",NaN
1031133,8485900057,Rimas y leyendas (ClÃƒÂ¡sicos Fraile ; 3),Gustavo Adolfo BÃƒÂ©cquer,1981,Ediciones Fraile,http://images.amazon.com/images/P/8485900057.0...,http://images.amazon.com/images/P/8485900057.0...,http://images.amazon.com/images/P/8485900057.0...,259614,10,"madrid, madrid, spain",22.0
1031134,0838934854,Anglo-American Cataloguing Rules,Michael Gorman,1998,American Library Association,http://images.amazon.com/images/P/0838934854.0...,http://images.amazon.com/images/P/0838934854.0...,http://images.amazon.com/images/P/0838934854.0...,259679,6,"grand prairie, texas, usa",27.0
1031135,3423300965,Texte zur Ethik.,Dieter Birnbacher,2003,Dtv,http://images.amazon.com/images/P/3423300965.0...,http://images.amazon.com/images/P/3423300965.0...,http://images.amazon.com/images/P/3423300965.0...,259920,0,"bielefeld, nordrhein-westfalen, germany",NaN

In [101]:
# import pickle
# pickle.dump(final_df,open('books_data.pkl','wb'))

In [102]:
# pickle.dump(books,open('books.pkl','wb'))
# pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [114]:
import pickle
import numpy as np

def recommend(book_name):
    index = np.where(pivot_final.index == book_name)[0][0]
    similar_item = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]
    data = []
    for i in similar_item:
        temp_df =  book_dict[book_dict['Book-Title'] == pivot_final.index[i[0]]]
        item = []
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        data.append(item)
    return data
book_dict = pickle.load(open(r'collaborative_recommend\books.pkl','rb'))
similarity_scores = pickle.load(open(r'collaborative_recommend\similarity_scores.pkl','rb'))
pivot_final = pickle.load(open('books_data.pkl','rb'))
    # return [i[0] for i in data],[i[1] for i in data],[i[2] for i in data]

In [115]:
recommend("The Handmaid's Tale")

[['AGE OF INNOCENCE (MOVIE TIE-IN)',
  'Edith Wharton',
  'http://images.amazon.com/images/P/002026478X.01.MZZZZZZZ.jpg'],
 ['The Bone Collector (Lincoln Rhyme Novels (Paperback))',
  'Jeff Deaver',
  'http://images.amazon.com/images/P/0451188454.01.MZZZZZZZ.jpg'],
 ['Bastard Out of Carolina',
  'Dorothy Allison',
  'http://images.amazon.com/images/P/0452269571.01.MZZZZZZZ.jpg'],
 ['The Awakening',
  'Kate Chopin',
  'http://images.amazon.com/images/P/055321330X.01.MZZZZZZZ.jpg'],
 ["The Kitchen God's Wife",
  'Amy Tan',
  'http://images.amazon.com/images/P/0399135782.01.MZZZZZZZ.jpg']]